In [4]:
from math_area import area as ar

In [5]:
ar.area_rect(7,8)

56

In [6]:
ar.area_cir(5)

78.5

In [7]:
import numpy as np

In [8]:
a = np.array([1,2,3,4,5])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [9]:
a[0:4]

array([1, 2, 3, 4])

### 2D array

In [10]:
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(b.shape)


(3, 3)


In [11]:
b[1:,1:]

array([[5, 6],
       [8, 9]])

In [12]:
c = np.array([[[1,1,1],
               [2,2,2],
               [3,3,3]],
              
              [[4,4,4],
               [5,5,5],
               [6,6,6]]])

print(c)

[[[1 1 1]
  [2 2 2]
  [3 3 3]]

 [[4 4 4]
  [5 5 5]
  [6 6 6]]]


In [16]:
print(c[1:,2:])


[[[6 6 6]]]


In [1]:
'''Numeric calculator'''

'''
Performs only:
1. ADD (+)
2. SUBTRACT (-)
3. MULTIPLY (*)
4. DIVIDE (/)\n'''

a = eval(input("Enter num1:"))
opr = str(input("Enter operation:"))[-1]
b = eval(input("Enter num2:"))

print(a,opr,b)

if opr=="+":
    print("=",a+b)
elif opr=="-":
    print("=",a-b)
elif opr=="*":
    print("=",a*b)
elif opr=="/":
    if b!=0:
        print("=",a/b)
    else:
        print("Check value of denominator!")
else:
    print("Invalid Operation!")

10 * 10
= 100
